// Job Notification Tracker - Realistic Indian Tech Jobs Dataset
const jobsData = [
  {
    id: 1,
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
    description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems and learn from experienced engineers. Strong problem-solving skills required."
  },
  {
    id: 2,
    title: "Graduate Engineer Trainee",
    company: "Infosys",
    location: "Mysore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Communication"],
    source: "Naukri",
    postedDaysAgo: 1,
    salaryRange: "3–5 LPA",
    applyUrl: "https://infosys.com/careers/get",
    description: "Infosys is hiring fresh graduates for our training program. Comprehensive training provided in latest technologies. Great learning opportunity for beginners."
  },
  {
    id: 3,
    title: "Frontend Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://razorpay.com/jobs/frontend-intern",
    description: "Build beautiful payment interfaces at Razorpay. Work with modern frontend stack and contribute to products used by millions of businesses across India."
  },
  {
    id: 4,
    title: "Junior Backend Developer",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://careers.swiggy.com/backend-dev",
    description: "Join Swiggy's backend team to build scalable food delivery systems. Work on high-traffic applications and learn distributed systems at scale."
  },
  {
    id: 5,
    title: "QA Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "API Testing"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://flipkart.com/careers/qa-intern",
    description: "Ensure quality of India's leading e-commerce platform. Learn testing methodologies and automation frameworks from experienced QA professionals."
  },
  {
    id: 6,
    title: "Data Analyst Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://phonepe.com/careers/data-analyst",
    description: "Analyze payment data and generate insights at PhonePe. Work with large datasets and help drive business decisions through data-driven insights."
  },
  {
    id: 7,
    title: "Java Developer (0-1)",
    company: "TCS",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://tcs.com/careers/java-developer",
    description: "Develop enterprise applications using Java and Spring framework. Work on banking and financial services projects with global clients."
  },
  {
    id: 8,
    title: "Python Developer (Fresher)",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://wipro.com/careers/python-dev",
    description: "Join Wipro's Python development team. Build web applications and automation tools for enterprise clients. Training provided for freshers."
  },
  {
    id: 9,
    title: "React Developer (1-3)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Redux", "TypeScript"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zoho.com/careers/react-developer",
    description: "Build modern web applications for Zoho's suite of products. Work with cutting-edge frontend technologies and contribute to products used globally."
  },
  {
    id: 10,
    title: "DevOps Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Docker", "AWS", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://cred.club/careers/devops-intern",
    description: "Learn DevOps practices at CRED. Work with cloud infrastructure, CI/CD pipelines, and modern deployment strategies in a fast-paced fintech environment."
  },
  {
    id: 11,
    title: "Full Stack Developer",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://freshworks.com/careers/fullstack",
    description: "Build SaaS products at Freshworks. Work on both frontend and backend, contributing to customer engagement and support platforms used worldwide."
  },
  {
    id: 12,
    title: "Mobile App Developer",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React Native", "Android", "iOS"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://paytm.com/careers/mobile-dev",
    description: "Develop mobile applications for Paytm's payment and financial services. Work on features used by millions of users daily across India."
  },
  {
    id: 13,
    title: "UI/UX Designer Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Figma", "UI Design", "Prototyping"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://juspay.in/careers/ui-ux-intern",
    description: "Design payment experiences at Juspay. Learn from experienced designers and contribute to products that power payments for major e-commerce platforms."
  },
  {
    id: 14,
    title: "Backend Engineer",
    company: "Accenture",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Microservices", "Kafka"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://accenture.com/careers/backend-engineer",
    description: "Build microservices architecture for enterprise clients. Work with modern backend technologies and distributed systems at scale."
  },
  {
    id: 15,
    title: "Data Science Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Machine Learning", "Pandas"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://ibm.com/careers/data-science-intern",
    description: "Apply machine learning to real-world problems at IBM. Work with data scientists and learn industry-standard ML practices and tools."
  },
  {
    id: 16,
    title: "Cloud Engineer",
    company: "Oracle",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["AWS", "Kubernetes", "Terraform"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://oracle.com/careers/cloud-engineer",
    description: "Build and maintain cloud infrastructure for Oracle Cloud. Work with cutting-edge cloud technologies and enterprise-scale deployments."
  },
  {
    id: 17,
    title: "Software Engineer Trainee",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Problem Solving"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://capgemini.com/careers/trainee",
    description: "Start your career with Capgemini's comprehensive training program. Learn enterprise software development and work on global projects."
  },
  {
    id: 18,
    title: "Frontend Developer",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Angular", "TypeScript", "SASS"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://sap.com/careers/frontend-developer",
    description: "Develop enterprise UI applications for SAP products. Work with modern frontend frameworks and contribute to business software used globally."
  },
  {
    id: 19,
    title: "Security Analyst Intern",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Cybersecurity", "Network Security", "Linux"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://cognizant.com/careers/security-intern",
    description: "Learn cybersecurity practices at Cognizant. Work on security assessments and vulnerability analysis for enterprise clients."
  },
  {
    id: 20,
    title: "Machine Learning Engineer",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "TensorFlow", "Deep Learning"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://dell.com/careers/ml-engineer",
    description: "Build ML models for Dell's product optimization. Work on computer vision and NLP projects with real-world business impact."
  },
  {
    id: 21,
    title: "Product Analyst Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Analytics"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://meesho.com/careers/product-analyst",
    description: "Analyze product metrics and user behavior at Meesho. Help drive product decisions through data analysis and A/B testing insights."
  },
  {
    id: 22,
    title: "iOS Developer",
    company: "Ola",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Swift", "iOS SDK", "UIKit"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://ola.com/careers/ios-developer",
    description: "Build iOS applications for Ola's mobility platform. Work on features that impact millions of riders and drivers across India."
  },
  {
    id: 23,
    title: "Android Developer",
    company: "Zomato",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kotlin", "Android SDK", "MVVM"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://zomato.com/careers/android-dev",
    description: "Develop Android applications for Zomato's food delivery platform. Work with modern Android architecture and contribute to user-facing features."
  },
  {
    id: 24,
    title: "Technical Writer Intern",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Technical Writing", "API Documentation", "Markdown"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://postman.com/careers/tech-writer",
    description: "Create API documentation and developer guides at Postman. Learn technical writing best practices and contribute to documentation used by developers worldwide."
  },
  {
    id: 25,
    title: "Backend Developer",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "FastAPI", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://dunzo.com/careers/backend-dev",
    description: "Build backend services for Dunzo's quick commerce platform. Work on real-time systems and learn about high-availability architectures."
  },
  {
    id: 26,
    title: "Graduate Engineer",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "C++", "Data Structures"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://lntinfotech.com/careers/graduate",
    description: "Join L&T Infotech's engineering team. Work on diverse projects across banking, insurance, and manufacturing domains with comprehensive training."
  },
  {
    id: 27,
    title: "Site Reliability Engineer",
    company: "Uber",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Python", "Monitoring"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://uber.com/careers/sre",
    description: "Ensure reliability of Uber's platform in India. Work on monitoring, incident response, and infrastructure automation at massive scale."
  },
  {
    id: 28,
    title: "Quality Assurance Engineer",
    company: "Tech Mahindra",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Selenium", "Java", "TestNG"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://techmahindra.com/careers/qa-engineer",
    description: "Automate testing for enterprise applications. Learn test automation frameworks and contribute to quality assurance for telecom and banking clients."
  },
  {
    id: 29,
    title: "Data Engineer",
    company: "Myntra",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Spark", "Hadoop", "Python"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://myntra.com/careers/data-engineer",
    description: "Build data pipelines for Myntra's fashion e-commerce platform. Work with big data technologies and enable data-driven decision making."
  },
  {
    id: 30,
    title: "Blockchain Developer Intern",
    company: "Polygon",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Solidity", "Ethereum", "Web3"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://polygon.technology/careers/blockchain-intern",
    description: "Learn blockchain development at Polygon. Work on Web3 projects and contribute to Ethereum scaling solutions used by major DeFi protocols."
  },
  {
    id: 31,
    title: "Software Developer",
    company: "HCL Technologies",
    location: "Noida",
    mode: "Onsite",
    experience: "0-1",
    skills: ["C#", ".NET", "SQL Server"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://hcltech.com/careers/software-developer",
    description: "Develop enterprise applications using Microsoft technologies. Work on projects for global clients in healthcare and financial services sectors."
  },
  {
    id: 32,
    title: "Game Developer Intern",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Unity", "C#", "Game Design"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://dream11.com/careers/game-dev-intern",
    description: "Build gaming features for India's largest fantasy sports platform. Learn game development and work on features used by millions of users."
  },
  {
    id: 33,
    title: "Network Engineer",
    company: "Cisco",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Networking", "CCNA", "Routing"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://cisco.com/careers/network-engineer",
    description: "Design and maintain network infrastructure for enterprise clients. Work with Cisco technologies and learn advanced networking concepts."
  },
  {
    id: 34,
    title: "Business Analyst Intern",
    company: "Deloitte",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Excel", "SQL", "Business Analysis"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://deloitte.com/careers/ba-intern",
    description: "Analyze business processes and provide insights at Deloitte. Work with consulting teams on projects for Fortune 500 companies."
  },
  {
    id: 35,
    title: "Embedded Systems Engineer",
    company: "Bosch",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["C", "Embedded C", "Microcontrollers"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://bosch.com/careers/embedded-engineer",
    description: "Develop embedded software for automotive systems. Work on IoT devices and learn real-time operating systems in a hardware-focused environment."
  },
  {
    id: 36,
    title: "Content Writer Intern",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Content Writing", "SEO", "Research"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://unacademy.com/careers/content-writer",
    description: "Create educational content for India's largest learning platform. Write engaging course materials and help millions of students learn effectively."
  },
  {
    id: 37,
    title: "Full Stack Engineer",
    company: "Groww",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://groww.in/careers/fullstack-engineer",
    description: "Build investment and trading platforms at Groww. Work on fintech products that democratize investing for millions of Indians."
  },
  {
    id: 38,
    title: "Automation Engineer",
    company: "Siemens",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "Selenium", "Jenkins"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://siemens.com/careers/automation-engineer",
    description: "Automate testing and deployment processes for industrial software. Learn CI/CD practices and work on automation for manufacturing systems."
  },
  {
    id: 39,
    title: "Research Intern",
    company: "Microsoft Research",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Research", "Machine Learning"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://microsoft.com/research/careers/intern",
    description: "Conduct cutting-edge research in AI and machine learning. Work with PhD researchers on problems that push the boundaries of computer science."
  },
  {
    id: 40,
    title: "Systems Engineer",
    company: "Infosys",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Linux"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://infosys.com/careers/systems-engineer",
    description: "Join Infosys as a Systems Engineer. Work on diverse technology projects and receive comprehensive training in enterprise software development."
  },
  {
    id: 41,
    title: "DevOps Engineer",
    company: "Atlassian",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["AWS", "Docker", "Kubernetes"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://atlassian.com/careers/devops",
    description: "Build and maintain infrastructure for Atlassian products. Work with cloud-native technologies and enable continuous delivery at scale."
  },
  {
    id: 42,
    title: "Support Engineer Intern",
    company: "Salesforce",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Customer Support", "Salesforce", "Problem Solving"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://salesforce.com/careers/support-intern",
    description: "Provide technical support for Salesforce products. Learn CRM systems and help customers solve technical challenges with enterprise software."
  },
  {
    id: 43,
    title: "AI Engineer",
    company: "Nvidia",
    location: "Pune",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Python", "CUDA", "Deep Learning"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://nvidia.com/careers/ai-engineer",
    description: "Develop AI solutions using Nvidia's GPU technology. Work on computer vision and deep learning projects with cutting-edge hardware acceleration."
  },
  {
    id: 44,
    title: "Database Administrator",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Oracle DB", "SQL", "Database Management"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://oracle.com/careers/dba",
    description: "Manage and optimize Oracle databases for enterprise clients. Learn database administration and performance tuning for mission-critical systems."
  },
  {
    id: 45,
    title: "Product Manager Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Product Management", "Analytics", "Communication"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://flipkart.com/careers/pm-intern",
    description: "Learn product management at India's leading e-commerce company. Work with cross-functional teams and contribute to product strategy and roadmap."
  },
  {
    id: 46,
    title: "Cybersecurity Engineer",
    company: "Palo Alto Networks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Security", "Penetration Testing", "Firewalls"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://paloaltonetworks.com/careers/security-engineer",
    description: "Protect enterprise networks from cyber threats. Work with next-generation firewalls and learn advanced security practices at a leading cybersecurity company."
  },
  {
    id: 47,
    title: "Software Test Engineer",
    company: "Qualcomm",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Testing", "Python", "Automation"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://qualcomm.com/careers/test-engineer",
    description: "Test mobile chipset software at Qualcomm. Work on cutting-edge mobile technology and ensure quality of products used in smartphones worldwide."
  },
  {
    id: 48,
    title: "Marketing Analyst Intern",
    company: "Google",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Analytics", "SQL", "Marketing"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://google.com/careers/marketing-analyst",
    description: "Analyze marketing campaigns and user behavior at Google. Work with large datasets and help optimize marketing strategies for Google products."
  },
  {
    id: 49,
    title: "Firmware Engineer",
    company: "Intel",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["C", "Firmware", "Hardware"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "10–18 LPA",
    applyUrl: "https://intel.com/careers/firmware-engineer",
    description: "Develop firmware for Intel processors. Work at the intersection of hardware and software on products that power computers worldwide."
  },
  {
    id: 50,
    title: "Technical Support Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Customer Support", "Adobe Products", "Troubleshooting"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://adobe.com/careers/support-intern",
    description: "Provide technical support for Adobe Creative Cloud products. Help customers solve technical issues and learn about creative software at scale."
  },
  {
    id: 51,
    title: "Backend Engineer",
    company: "Stripe",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["Ruby", "Go", "Distributed Systems"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://stripe.com/careers/backend-engineer",
    description: "Build payment infrastructure at Stripe. Work on systems that process billions of dollars and learn about financial technology at global scale."
  },
  {
    id: 52,
    title: "Graduate Trainee",
    company: "Mahindra Tech",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Communication"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://mahindratech.com/careers/trainee",
    description: "Begin your career with Mahindra Tech's training program. Work on automotive and manufacturing software with comprehensive mentorship."
  },
  {
    id: 53,
    title: "AR/VR Developer",
    company: "Meta",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Unity", "C#", "3D Graphics"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://meta.com/careers/arvr-developer",
    description: "Build immersive experiences for Meta's VR platforms. Work on cutting-edge AR/VR technology and shape the future of virtual reality."
  },
  {
    id: 54,
    title: "Sales Engineer Intern",
    company: "Twilio",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["APIs", "Communication", "Technical Demos"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://twilio.com/careers/sales-engineer-intern",
    description: "Bridge technical and business teams at Twilio. Learn about communication APIs and help customers integrate Twilio into their products."
  },
  {
    id: 55,
    title: "Platform Engineer",
    company: "Airbnb",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Kubernetes", "Go", "Infrastructure"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "10–18 LPA",
    applyUrl: "https://airbnb.com/careers/platform-engineer",
    description: "Build platform infrastructure for Airbnb's global marketplace. Work on tools and systems that enable engineering teams to ship faster."
  },
  {
    id: 56,
    title: "Junior Data Scientist",
    company: "Walmart Labs",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "Machine Learning", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://walmartlabs.com/careers/data-scientist",
    description: "Apply data science to retail problems at Walmart Labs. Build recommendation systems and forecasting models for e-commerce at massive scale."
  },
  {
    id: 57,
    title: "Solutions Architect Intern",
    company: "AWS",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["AWS", "Cloud Architecture", "Networking"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://aws.amazon.com/careers/solutions-architect",
    description: "Learn cloud architecture at AWS. Work with customers to design scalable cloud solutions and gain hands-on experience with AWS services."
  },
  {
    id: 58,
    title: "Performance Engineer",
    company: "LinkedIn",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Performance Testing", "Profiling"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "10–18 LPA",
    applyUrl: "https://linkedin.com/careers/performance-engineer",
    description: "Optimize performance of LinkedIn's platform. Work on profiling, load testing, and ensuring the platform scales for millions of users."
  },
  {
    id: 59,
    title: "Integration Engineer",
    company: "MuleSoft",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["APIs", "Integration", "MuleSoft"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://mulesoft.com/careers/integration-engineer",
    description: "Build API integrations using MuleSoft platform. Connect enterprise systems and learn about integration patterns at scale."
  },
  {
    id: 60,
    title: "Scrum Master Intern",
    company: "ThoughtWorks",
    location: "Pune",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Agile", "Scrum", "Project Management"],
    source: "Naukri",
    postedDaysAgo: 0,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://thoughtworks.com/careers/scrum-master",
    description: "Learn agile methodologies at ThoughtWorks. Facilitate scrum ceremonies and help teams deliver software effectively using agile practices."
  }
];
